language: go

os: linux

go:
  - tip
  - 1.12.x
  - 1.13.x
  - 1.14.x

before_script:
  - docker-compose -f test/docker/docker-compose.yml up -d
script:
  - test/scripts/coverage.sh
after_script:
  - docker-compose -f test/docker/docker-compose.yml down

after_success:
  - bash <(curl -s https://codecov.io/bash)
